account/urls.py
from django.urls import path

from .views import (LoginView, LogoutView, RegisterView, ValidateView, ProfileView, ResendValidationView,
                    PasswordResetView, PasswordResetConfirmView, CookiesView, PasswordChangeView, AccountDeleteView,
                    AccountUpdateView)


app_name = 'account'

urlpatterns = [
    path('create-account/', RegisterView.as_view(), name='register'),
    path('validate/<slug:uidb64>/<slug:token>/', ValidateView.as_view(), name='validate'),
    path('validate/', ResendValidationView.as_view(), name='resend_validate'),
    path('login/', LoginView.as_view(), name='login'),
    path('login/password/', PasswordResetView.as_view(), name='password_reset'),
    path('login/password/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', AccountUpdateView.as_view(), name='update'),
    path('account/password/', PasswordChangeView.as_view(), name='password'),
    path('account/delete/', AccountDeleteView.as_view(), name='delete'),
    path('cookies/', CookiesView.as_view(), name='cookies'),
    path('<slug:slug>/', ProfileView.as_view(), name='profile'),
]

api/urls.py
from django.urls import (path, include)
from rest_framework import routers

from .views import (OfferViewSet, UserViewSet, AuctionViewSet, BidViewSet, CategoryViewSet)


router = routers.DefaultRouter()
router.register(r'auctions', AuctionViewSet)
router.register(r'bids', BidViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'offers', OfferViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

bid/urls.py
from django.urls import path

from .views import (BidListView, BidWinView, BidUpdateView, BidDeleteView, BidEmailView, BidValidateView,
                    BidRemovePinchHitterView, BidAlertEmailView, BidConfirmEmailView, BidBulkAlertEmailView,
                    BidDonationView)


app_name = 'bid'

urlpatterns = [
    path('<slug:user>/<slug:auction>/results/bulk-email/', BidBulkAlertEmailView.as_view(), name='email_bulk_alert'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/', BidEmailView.as_view(), name='email'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/alert/', BidAlertEmailView.as_view(), name='email_alert'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/',
         BidConfirmEmailView.as_view(to_winner=True, to_auctionee=True),
         name='email_confirm'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/winner/', BidConfirmEmailView.as_view(to_winner=True), name='email_confirm_to_winner'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/auctionee/', BidConfirmEmailView.as_view(to_auctionee=True), name='email_confirm_to_auctionee'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/validate/', BidValidateView.as_view(), name='validate'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/remove-pinch-hit/',
         BidRemovePinchHitterView.as_view(),
         name='remove_pinch_hit'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/edit/', BidUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/delete/', BidDeleteView.as_view(), name='delete'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/bids/', BidListView.as_view(), name='list'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/wins/', BidWinView.as_view(), name='wins'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/wins/<slug:hash>/', BidDonationView.as_view(), name='donate'),
]

fantics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import (include, path)
from django.views.generic import RedirectView


urlpatterns = [
    path('hijack/', include('hijack.urls', namespace='hijack')),
    # path('api/v1/', include('api.urls')),
    path('', include('main.urls', namespace="main")),
    path('', include('message.urls', namespace="message")),
    path('', include('account.urls', namespace="account")),
    path('', include('auction.urls', namespace="auction")),
    path('', include('bid.urls', namespace="bid")),
    path('', include('category.urls', namespace="category")),
    path('', include('offer.urls', namespace="offer")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
        + urlpatterns

offer/urls.py
from django.urls import path

from .views import (OfferView, OfferCreateView, OfferListView, OfferUpdateView, OfferDeleteView,
                    OfferListAdministrationView, OfferUpdateAdministrationView, OfferDeleteAdministrationView,
                    OfferSearchView)


app_name = 'offer'

urlpatterns = [
    path('<slug:user>/<slug:auction>/create-offer/', OfferCreateView.as_view(), name='create'),
    path('<slug:user>/<slug:auction>/offers/', OfferListAdministrationView.as_view(), name='list_administration'),
    path('<slug:user>/<slug:auction>/offers/<slug:category>/', OfferListAdministrationView.as_view(),
         name='list_administration_category'),
    path('<slug:user>/<slug:auction>/offer/<int:pk>/edit/', OfferUpdateAdministrationView.as_view(),
         name='update_administration'),
    path('<slug:user>/<slug:auction>/offer/<int:pk>/delete/', OfferDeleteAdministrationView.as_view(),
         name='delete_administration'),
    path('<slug:user>/<slug:auction>/tag:<slug:tag>/', OfferSearchView.as_view(), name='search_tag'),
    path('<slug:user>/<slug:auction>/category:<slug:category>/', OfferSearchView.as_view(), name='search_category'),
    path('<slug:user>/<slug:auction>/category:<slug:category>/tag:<slug:tag>/', OfferSearchView.as_view(),
         name='search_items'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/', OfferListView.as_view(), name='list'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/', OfferView.as_view(), name='view'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/edit/', OfferUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/delete/', OfferDeleteView.as_view(), name='delete'),
]

offer/models.py
from decimal import Decimal

from django.db import models
from django.db.models.functions import Lower
from django.utils.functional import cached_property

from taggit.managers import TaggableManager

from bid.models import Bid
from core.helpers import file_name
from tags.models import FanticsTaggedItem


class OfferManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .select_related('user') \
            .select_related('category') \
            .prefetch_related('tags') \
            .order_by(Lower('user__display_name')) \
            .annotate(
                count_bids=models.Count('bids', distinct=True)
            )


def offer_image_name(instance, filename):
    return '/'.join(['offers', file_name(filename)])


class Offer(models.Model):
    user = models.ForeignKey('account.User', related_name='offers', on_delete=models.PROTECT)
    auction = models.ForeignKey('auction.Auction', related_name='offers', on_delete=models.PROTECT)
    category = models.ForeignKey('category.Category', related_name='offers', on_delete=models.PROTECT)
    notes = models.TextField(blank=False)
    tags = TaggableManager(through=FanticsTaggedItem, blank=True)
    deadline = models.DateField(null=True, blank=True, help_text='The date by which you will have delivered the offer '
                                                                 'to the winning bidder(s)')
    minimum_bid = models.DecimalField(blank=True, max_digits=8, decimal_places=2, default=Decimal('1.00'))
    quantity = models.IntegerField(default=1, help_text="How many of the item you're offering can be individually bid "
                                                        "on")
    image = models.ImageField(null=True, blank=True, upload_to=offer_image_name)
    information_website = models.URLField(blank=True, max_length=255)

    objects = OfferManager()

    @cached_property
    def _bids(self):
        return self.bids.all()

    @property
    def top_bids(self):
        return self._bids[:self.quantity] if self.count_bids else []

    @property
    def must_bid(self):
        try:
            return Decimal(self.top_bids[self.quantity-1].amount + 1)
        except IndexError:
            return self.minimum_bid

    @property
    def total(self):
        total = 0

        for bid in self.top_bids:
            if bid.has_donated:
                total += bid.amount

        return total

    def __str__(self):
        return "{}: {} (x{})".format(self.user.display_name, self.category.name, self.quantity)

offer/forms.py
from django import forms

from tags.fields import FanticsTagField

from .models import Offer


class OfferForm(forms.ModelForm):
    deadline = forms.DateField(input_formats=["%m/%d/%Y", ], required=False)
    information_website = forms.URLField(widget=forms.URLInput(attrs={'placeholder': 'http://'}), required=False)
    tags = FanticsTagField(required=False)
    minimum_bid = forms.IntegerField(widget=forms.NumberInput(attrs={'step': 0.01, 'min': 1}))

    class Meta:
        model = Offer
        fields = ['category', 'notes', 'deadline', 'minimum_bid', 'quantity', 'tags', 'image', 'information_website']

    def __init__(self, **kwargs):
        self.auction = None

        if 'auction' in kwargs:
            self.auction = kwargs.pop('auction')

        super().__init__(**kwargs)

        if self.auction and self.auction.max_quantity_per_offer:
            self.fields['quantity'] = forms.IntegerField(
                widget=forms.Select(choices=[(x+1, x+1) for x in range(self.auction.max_quantity_per_offer)])
            )

        self.fields['minimum_bid'].label = "Minimum bid ({})".format(self.auction.currency)

    def clean_deadline(self):
        if self.cleaned_data.get('deadline') and self.cleaned_data.get('deadline') < self.auction.bidding_ends.date():
            raise forms.ValidationError('The deadline must be after bidding ends', 'invalid', params=['deadline', ])

        return self.cleaned_data.get('deadline')

    def clean_minimum_bid(self):
        if not self.cleaned_data.get('minimum_bid') or self.cleaned_data.get('minimum_bid') < 1:
            self.cleaned_data.update({'minimum_bid': 1})

        return self.cleaned_data.get('minimum_bid')


class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'type': 'search', 'placeholder': 'Keywords'}))

offer/templates/offer/_offer_card.html
{% load core_tags %}

<div class="col-md-4 my-3">
    <div class="card">
        <div class="card-header">
            <a href="{% url 'offer:search_category' auction.user.slug auction.slug offer.category.slug %}">{{ offer.category }}</a>
            <span class="float-right">
                {% if auction.is_archived %}
                    <strong>{% currency offer.total auction.currency %}</strong>
                {% elif offer.count_bids %}
                    <strong>{% currency offer.must_bid auction.currency %}</strong>
                {% else %}
                    <strong>{% currency offer.minimum_bid auction.currency %}</strong>
                {% endif %}
            </span>
        </div>
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'offer:list' auction.user.slug auction.slug offer.user.slug %}">{{ offer.user }}</a></h5>
            <p class="card-text">{{ offer.notes }}</p>
            <div class="row">
                <div class="col-md-6">
                    <a href="{% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}" class="btn btn-primary">View</a>
                </div>
                <div class="col-md-6 text-md-right">
                    {% if auction.bidding_open and request.user.is_authenticated %}
                        <a href="{% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}#Bid" class="btn btn-warning">Bid!</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-footer ellipsis">
            {% for tag in offer.tags.all %}
                <small><a href="{% url 'offer:search_tag' auction.user.slug auction.slug tag.slug %}" class="text-muted">#{{ tag }}</a></small>
            {% endfor %}
        </div>
    </div>
</div>

offer/templates/offer/_update_form.html
{% load bootstrap4 core_tags %}

{% csrf_token %}

{% bootstrap_form_errors form %}
<fieldset>
    <legend>Offer</legend>
    {% bootstrap_field form.category layout="horizontal" %}
    {% bootstrap_field form.minimum_bid layout="horizontal" %}
    {% bootstrap_field form.quantity layout="horizontal" %}
    {% if auction.allow_custom_offer_deadline %}
    {% datetimepicker 'deadline' label='Deadline' mode="date" %}
    <div class="row pb-3">
        <label class="col-md-3"></label>
        <div class="col-md-9">
            <small class="form-text text-muted">The date by which you will have delivered the offer to the winning bidder(s).
                Leave blank to use the auction default ({{ auction.offer_deadline|date:"F jS Y"|default_if_none:"no deadline" }}).
            </small>
        </div>
    </div>
    {% endif %}
</fieldset>

<fieldset>
    <legend>About</legend>
    {% bootstrap_field form.notes layout="inline" %}
    {% bootstrap_field form.information_website layout="horizontal" %}
    {% bootstrap_field form.image layout="horizontal" %}
</fieldset>

<fieldset>
    <legend>Tags</legend>
    {% bootstrap_field form.tags layout="inline" %}
</fieldset>

<button type="submit" class="btn btn-primary">Edit</button>

offer/templates/offer/_view_about.html
{% load core_tags %}
<hr>
<p>
    <strong>{{ offer.quantity }}</strong> item{% if offer.quantity > 1%}s{% endif %} can be bid on, delivery by <strong>{{ offer.deadline|default_if_none:auction.offer_deadline }}</strong>.
</p>

{% if offer.notes or offer.information_website %}
<hr>
{% endif %}

{% if offer.notes %}
<p>{{ offer.notes|linebreaksbr }}</p>
{% endif %}

{% if offer.information_website %}
<p><i class="fa fa-external-link-square"></i> <a href="{{ offer.information_website }}" target="_blank">More information</a></p>
{% endif %}

offer/templates/offer/browse.html
{% extends 'auction/base.html' %}
{% load bootstrap4 core_tags %}

{% block content %}

    <h1>{{ user }}'s offers</h1>

    {% if offer_list %}
        <div class="row">
            {% for offer in offer_list %}
                {% include "offer/_offer_card.html" %}
            {% endfor %}
        </div>
    {% else %}
        <p class="alert alert-info">{{ user }} has no offers in this auction</p>
    {% endif %}

{% endblock %}

offer/templates/offer/create.html
{% extends 'auction/base.html' %}
{% load bootstrap4 core_tags %}

{% block javascript_body %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css">
{% endblock %}

{% block content %}
    <h1>Add offer to {{ auction }}</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'offer:create' auction.user.slug auction.slug %}">
        {% csrf_token %}
        {% bootstrap_form_errors form %}
        <fieldset>
            <legend>Offer</legend>
            {% bootstrap_field form.category layout="horizontal" %}
            {% bootstrap_field form.minimum_bid layout="horizontal" %}
            {% bootstrap_field form.quantity layout="horizontal" %}
            {% if auction.allow_custom_offer_deadline %}
            {% datetimepicker 'deadline' label='Deadline' mode="date" %}
            <div class="row pb-3">
                <label class="col-md-3"></label>
                <div class="col-md-9">
                    <small class="form-text text-muted">The date by which you will have delivered the offer to the winning bidder(s).
                        Leave blank to use the auction default ({{ auction.offer_deadline|date:"F jS Y"|default_if_none:"no deadline" }}).
                    </small>
                </div>
            </div>
            {% endif %}
        </fieldset>

        <fieldset>
            <legend>About</legend>
            {% bootstrap_field form.notes layout="inline" %}
            {% bootstrap_field form.information_website layout="horizontal" %}
            {% bootstrap_field form.image layout="horizontal" %}
        </fieldset>

        <fieldset>
            <legend>Tags</legend>
            {% bootstrap_field form.tags layout="inline" %}
        </fieldset>

        <button type="submit" class="btn btn-primary">Create</button>
    </form>
{% endblock %}

offer/templates/offer/delete.html
{% extends 'auction/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete your offer for <strong>{{ offer.category|lower }}</strong>? Once you hit the button below, it's gone-gone. Like, gone like it never was, <strong>gone</strong>.</p>
    <button type="submit" class="btn btn-danger">Super sure! Delete it!</button>
    <a class="btn btn-primary float-right" href="{% url 'offer:list' auction.user.slug auction.slug request.user.slug %}">Augh, stop, reverse! Reverse!</a>
</form>
{% endblock %}

offer/templates/offer/list.html
{% extends 'auction/base.html' %}
{% load bootstrap4 core_tags %}

{% block content %}

    <h1>Your offers</h1>

    {% if auction.signups_open %}
        {% if not auction.max_offers_per_user or offer_list|length < auction.max_offers_per_user %}
            <p class="text-right">
                <a href="{% url 'offer:create' auction.user.slug auction.slug %}" class="btn btn-primary">
                    <i class="fa fa-plus-square"></i> Add offer
                </a>
            </p>
        {% endif %}
    {% endif %}

    {% if offer_list %}
        <table class="table">
            <thead>
                <tr>
                    <th>Offer</th>
                    <th>Minimum bid</th>
                    <th>Quantity</th>
                    <th>Deadline</th>
                    <th>Bids</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for offer in offer_list %}
                    <tr>
                        <td>{{ offer.category.name }}</td>
                        <td>{% currency offer.minimum_bid auction.currency %}</td>
                        <td>{{ offer.quantity }}</td>
                        <td>{{ offer.deadline|default_if_none:auction.offer_deadline }}</td>
                        <td>{{ offer.count_bids|default_if_none:0 }}</td>
                        <td class="text-right">
                            <div class="btn-group" role="group" aria-label="Administration">
                                <a class="btn btn-success" href="{% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}" title="View">
                                    <i class="fa fa-eye"></i> <span class="sr-only">View</span>
                                </a>
                                {% if auction.signups_open %}
                                <a class="btn btn-info" href="{% url 'offer:update' auction.user.slug auction.slug request.user.slug offer.pk %}" title="Edit">
                                    <i class="fa fa-pencil"></i> <span class="sr-only">Edit</span>
                                </a>
                                <a class="btn btn-warning" href="{% url 'offer:delete' auction.user.slug auction.slug request.user.slug offer.pk %}" title="Delete">
                                    <i class="fa fa-trash"></i> <span class="sr-only">Delete</span>
                                </a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="alert alert-info">You have no offers in this auction</p>
    {% endif %}

{% endblock %}

offer/templates/offer/update.html
{% extends 'auction/base.html' %}
{% load bootstrap4 core_tags %}

{% block javascript_body %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css">
{% endblock %}

{% block content %}
<h1>Edit {{ offer.category|lower }} offer</h1>

<form method="post" enctype="multipart/form-data" action="{% url 'offer:update' auction.user.slug auction.slug request.user.slug offer.pk %}">
    {% include "offer/_update_form.html" %}
</form>
{% endblock %}

offer/templates/offer/view.html
{% extends 'auction/base.html' %}
{% load bootstrap4 core_tags %}

{% block javascript_body %}
<script>
    var offerSocket = new WebSocket('ws://' + window.location.host + '/offer/{{ offer.pk }}/');
    var bidForm = $('#Bid');
    var bidConfirm = $('#BidConfirm');
        bidConfirm.hide();
    var user_id = {{ request.user.id|default_if_none:0 }};

    bidForm.submit(function(e){
        e.preventDefault();
        $.ajax({
            type: "POST",
            url: bidForm.attr('action'),
            data: bidForm.serialize(),
            success: function(res) {
                if (res.success) {
                    offerSocket.send(JSON.stringify({'status': 1}));
                }
            }
        });
    });

    offerSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        $('#id_amount').val(data['must_bid']);
        $('#topBids').empty();
        bidConfirm.show().delay(5000).fadeOut();

        jQuery.each(data['top_bids'], function(index, value){
            var name = value['display_name'];

            if (value['anonymous'] && value['user_id'] !== user_id) {
                name = "Anonymous";
            }

            $('#topBids').append("<li class='list-group-item d-flex justify-content-between align-items-center'>" + name + "<strong>" + value['amount'] + "</strong></li>");
        });
    };

    offerSocket.onclose = function(e) {
        window.setTimeout(function(){
            window.location.href = "{% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}";
        }, 10000);
    };

</script>
{% endblock %}

{% block content %}

    <div class="row mb-3">
        <div class="col-md-9">
            <h1 class="mb-0">{{ offer.user }} {{ offer.category|lower }}</h1>
            {% if offer.tags.exists %}
                <h6 class="my-0">
                    {% for tag in offer.tags.all %}
                        <span><a href="{% url 'offer:search_tag' auction.user.slug auction.slug tag.slug %}">#{{ tag }}</a></span>
                    {% endfor %}
                </h6>
            {% endif %}
        </div>
        <div class="col-md-3 text-right">
        {% if auction.signups_open and request.user.id == offer.user.id %}
            <div class="btn-group">
                <a href="{% url 'offer:update' auction.user.slug auction.slug offer.user.slug offer.pk %}" class="btn btn-primary"><i class="fa fa-pencil"></i> Edit</a>
                <a href="{% url 'offer:delete' auction.user.slug auction.slug offer.user.slug offer.pk %}" class="btn btn-warning"><i class="fa fa-trash"></i> Delete</a>
            </div>
        {% elif auction.user.id == request.user.id %}
            <div class="btn-group">
                <a href="{% url 'offer:update_administration' auction.user.slug auction.slug offer.pk %}" class="btn btn-primary"><i class="fa fa-pencil"></i> Edit</a>
                <a href="{% url 'offer:delete_administration' auction.user.slug auction.slug offer.pk %}" class="btn btn-warning"><i class="fa fa-trash"></i> Delete</a>
            </div>
        {% endif %}
        </div>
    </div>

    {% if offer.image %}
        <div class="row">
            <div class="col-md-6">
                {% include "offer/_view_about.html" %}
            </div>
            <div class="col-md-6"><img src="/media/{{ offer.image }}" class="img-fluid"></div>
        </div>
    {% else %}
        {% include "offer/_view_about.html" %}
    {% endif %}

    <hr>

    <div class="row">
        <div class="col-md-6">
            {% if auction.bidding_open %}
                <h3>Bid</h3>

                {% if request.user.is_authenticated %}
                    <form method="post" id="Bid" action="{% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}">
                        {% csrf_token %}
                        <p class="alert alert-warning">
                            <small><i class="fa fa-exclamation-triangle"></i> Bids cannot be deleted and there is no confirmation stage.
                            {% if offer.quantity > 1 %} <strong>If you have a top bid and bid again, it will be considered a bid for an additional item!</strong>{% endif %}</small>
                        </p>

                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">{{ auction.currency }}</span>
                            </div>
                            <input type="text" name="amount" value="{{ offer.must_bid }}" step="0.01" class="form-control" placeholder="Amount" title="" id="id_amount">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">Bid!</button>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="form-check">
                                <input type="checkbox" name="anonymous" class="form-check-input" title="" id="id_anonymous">
                                <label class="form-check-label" for="id_anonymous">Anonymous</label>
                            </div>
                        </div>

                    </form>

                    <p class="alert alert-success" id="BidConfirm">Thank you for bidding!</p>

                {% else %}

                    <p class="alert alert-warning">You must be <a class="alert-link" href="{% url 'account:login' %}?next={% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}">logged in</a> to bid!</p>

                {% endif %}

            {% elif auction.bidding_period %}
                <h3>Bid</h3>
                <p>Bidding is open <strong>{{ auction.bidding_period }}</strong></p>

            {% endif %}
        </div>
        <div class="col-md-6">
            {% if offer.count_bids %}
                <h3>Top bids</h3>
                <ul id="topBids" class="list-group">
                    {% for bid in offer.top_bids %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {% if offer.quantity > 1 %}
                            {{ offer.category }} {{ forloop.counter }}:
                            {% endif %}
                            {% if not bid.anonymous or user.id == bid.user_id %}{{ bid.user }}{% else %}Anonymous{% endif %}
                            <strong>{% currency bid.amount auction.currency %}</strong>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>

{% endblock %}

offer/templates/offer/winners.html
{% extends 'auction/base.html' %}
{% load bootstrap4 core_tags %}

{% block main %}

    <h1>Your winners</h1>

    {% if offer_list %}

        <table class="table">
            <tbody>
                {% for bid in offer_list %}
                <tr class="table-{% if bid.donation_complete %}success{% elif bid.donation_unverified %}info{% elif bid.pending_alert %}light{% elif bid.pending_donation %}warning{% elif bid.donation_late %}danger{% endif %}">
                    <td>{{ bid.offer.category }}</td>
                    <td>
                        {% if bid.donation_complete or not bid.anonymous %}
                            <a href="{% url 'account:profile' bid.user.slug %}">{{ bid.user }}</a>
                        {% else %}
                            Anonymous
                        {% endif %}
                    </td>
                    <td>{% currency bid.amount auction.currency %}</td>
                    <td class="text-right">
                        <a href="{% url 'offer:view' auction.user.slug auction.slug bid.offer.user.slug bid.offer.pk %}" class="btn btn-info btn-sm" title="View"><i class="fa fa-eye"></i> <span class="sr-only">View</span></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    {% else %}

        <p class="alert alert-info">You have no offers in this auction</p>

    {% endif %}

{% endblock %}

{% block side %}

    <h1>&nbsp;</h1>

    <ul class="list-group">
        <li class="list-group-item list-group-item-light">Pending administration</li>
        <li class="list-group-item list-group-item-warning">Pending donation</li>
        <li class="list-group-item list-group-item-info">Donation unverified</li>
        <li class="list-group-item list-group-item-success">Donation complete</li>
        <li class="list-group-item list-group-item-danger">Donation late</li>
    </ul>

{% endblock %}