account/urls.py
from django.urls import path

from .views import (LoginView, LogoutView, RegisterView, ValidateView, ProfileView, ResendValidationView,
                    PasswordResetView, PasswordResetConfirmView, CookiesView, PasswordChangeView, AccountDeleteView,
                    AccountUpdateView)


app_name = 'account'

urlpatterns = [
    path('create-account/', RegisterView.as_view(), name='register'),
    path('validate/<slug:uidb64>/<slug:token>/', ValidateView.as_view(), name='validate'),
    path('validate/', ResendValidationView.as_view(), name='resend_validate'),
    path('login/', LoginView.as_view(), name='login'),
    path('login/password/', PasswordResetView.as_view(), name='password_reset'),
    path('login/password/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', AccountUpdateView.as_view(), name='update'),
    path('account/password/', PasswordChangeView.as_view(), name='password'),
    path('account/delete/', AccountDeleteView.as_view(), name='delete'),
    path('cookies/', CookiesView.as_view(), name='cookies'),
    path('<slug:slug>/', ProfileView.as_view(), name='profile'),
]

api/urls.py
from django.urls import (path, include)
from rest_framework import routers

from .views import (OfferViewSet, UserViewSet, AuctionViewSet, BidViewSet, CategoryViewSet)


router = routers.DefaultRouter()
router.register(r'auctions', AuctionViewSet)
router.register(r'bids', BidViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'offers', OfferViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

auction/urls.py
from django.urls import path

from .views import (AuctionView, AuctionAboutView, AuctionCreateView, AuctionUpdateView, AuctionDeleteView,
                    AuctionResultsView, AuctionUpdateEmailView, AuctionUpdateLayoutView)


app_name = 'auction'

urlpatterns = [
    path('<slug:user>/create-auction/', AuctionCreateView.as_view(), name='create'),
    path('<slug:user>/<slug:auction>/', AuctionView.as_view(), name='auction'),
    path('<slug:user>/<slug:auction>/about/', AuctionAboutView.as_view(), name='about'),
    path('<slug:user>/<slug:auction>/edit/', AuctionUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/edit/email/', AuctionUpdateEmailView.as_view(), name='update_email'),
    path('<slug:user>/<slug:auction>/edit/layout/', AuctionUpdateLayoutView.as_view(), name='update_layout'),
    path('<slug:user>/<slug:auction>/delete/', AuctionDeleteView.as_view(), name='delete'),
    path('<slug:user>/<slug:auction>/winning-bids/', AuctionResultsView.as_view(), name='results'),
]

bid/urls.py
from django.urls import path

from .views import (BidListView, BidWinView, BidUpdateView, BidDeleteView, BidEmailView, BidValidateView,
                    BidRemovePinchHitterView, BidAlertEmailView, BidConfirmEmailView, BidBulkAlertEmailView,
                    BidDonationView)


app_name = 'bid'

urlpatterns = [
    path('<slug:user>/<slug:auction>/results/bulk-email/', BidBulkAlertEmailView.as_view(), name='email_bulk_alert'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/', BidEmailView.as_view(), name='email'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/alert/', BidAlertEmailView.as_view(), name='email_alert'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/',
         BidConfirmEmailView.as_view(to_winner=True, to_auctionee=True),
         name='email_confirm'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/winner/', BidConfirmEmailView.as_view(to_winner=True), name='email_confirm_to_winner'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/auctionee/', BidConfirmEmailView.as_view(to_auctionee=True), name='email_confirm_to_auctionee'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/validate/', BidValidateView.as_view(), name='validate'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/remove-pinch-hit/',
         BidRemovePinchHitterView.as_view(),
         name='remove_pinch_hit'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/edit/', BidUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/delete/', BidDeleteView.as_view(), name='delete'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/bids/', BidListView.as_view(), name='list'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/wins/', BidWinView.as_view(), name='wins'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/wins/<slug:hash>/', BidDonationView.as_view(), name='donate'),
]

fantics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import (include, path)
from django.views.generic import RedirectView


urlpatterns = [
    path('hijack/', include('hijack.urls', namespace='hijack')),
    # path('api/v1/', include('api.urls')),
    path('', include('main.urls', namespace="main")),
    path('', include('message.urls', namespace="message")),
    path('', include('account.urls', namespace="account")),
    path('', include('auction.urls', namespace="auction")),
    path('', include('bid.urls', namespace="bid")),
    path('', include('category.urls', namespace="category")),
    path('', include('offer.urls', namespace="offer")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
        + urlpatterns

offer/urls.py
from django.urls import path

from .views import (OfferView, OfferCreateView, OfferListView, OfferUpdateView, OfferDeleteView,
                    OfferListAdministrationView, OfferUpdateAdministrationView, OfferDeleteAdministrationView,
                    OfferSearchView)


app_name = 'offer'

urlpatterns = [
    path('<slug:user>/<slug:auction>/create-offer/', OfferCreateView.as_view(), name='create'),
    path('<slug:user>/<slug:auction>/offers/', OfferListAdministrationView.as_view(), name='list_administration'),
    path('<slug:user>/<slug:auction>/offers/<slug:category>/', OfferListAdministrationView.as_view(),
         name='list_administration_category'),
    path('<slug:user>/<slug:auction>/offer/<int:pk>/edit/', OfferUpdateAdministrationView.as_view(),
         name='update_administration'),
    path('<slug:user>/<slug:auction>/offer/<int:pk>/delete/', OfferDeleteAdministrationView.as_view(),
         name='delete_administration'),
    path('<slug:user>/<slug:auction>/tag:<slug:tag>/', OfferSearchView.as_view(), name='search_tag'),
    path('<slug:user>/<slug:auction>/category:<slug:category>/', OfferSearchView.as_view(), name='search_category'),
    path('<slug:user>/<slug:auction>/category:<slug:category>/tag:<slug:tag>/', OfferSearchView.as_view(),
         name='search_items'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/', OfferListView.as_view(), name='list'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/', OfferView.as_view(), name='view'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/edit/', OfferUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/delete/', OfferDeleteView.as_view(), name='delete'),
]

bid/models.py
from decimal import Decimal

from django.conf import settings
from django.core.mail import EmailMessage
from django.db import models
from django.shortcuts import reverse
from django.utils import (timezone, dateformat)

from core.templatetags.core_tags import format_currency

from .settings import BID_HASH


class BidManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .select_related('user') \
            .select_related('pinch_hitter') \
            .select_related('offer') \
            .select_related('offer__category') \
            .select_related('offer__user') \
            .order_by('-amount')


class Bid(models.Model):
    MODES = [
        'donation_complete',
        'donation_unverified',
        'pending_alert',
        'pending_donation',
        'donation_late'
    ]

    user = models.ForeignKey('account.User', related_name='bids', on_delete=models.PROTECT)
    pinch_hitter = models.ForeignKey('account.User', related_name='pinch_hits', on_delete=models.PROTECT, null=True,
                                     blank=True)
    anonymous = models.BooleanField(default=False)
    offer = models.ForeignKey('offer.Offer', related_name='bids', on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(blank=True, max_digits=6, decimal_places=2, default=Decimal('0.00'))
    donation_deadline = models.DateTimeField(blank=True, null=True)
    winner_alert_email = models.TextField(blank=True)
    winner_alert_email_date = models.DateTimeField(blank=True, null=True)
    auctionee_sent_winner_details_email = models.TextField(blank=True)
    auctionee_sent_winner_details_email_date = models.DateTimeField(blank=True, null=True)
    winner_sent_auctionee_details_email = models.TextField(blank=True)
    winner_sent_auctionee_details_email_date = models.DateTimeField(blank=True, null=True)
    pinch_hitter_sent_winner_details_email = models.TextField(blank=True)
    pinch_hitter_sent_winner_details_email_date = models.DateTimeField(blank=True, null=True)
    winner_sent_pinch_hitter_details_email = models.TextField(blank=True)
    winner_sent_pinch_hitter_details_email_date = models.DateTimeField(blank=True, null=True)

    donated = models.DateTimeField(blank=True, null=True)
    receipt = models.TextField(blank=True)
    has_donated = models.BooleanField(default=False, db_index=True)

    objects = BidManager()

    def __str__(self):
        return str(self.amount)

    @property
    def donate_by(self):
        return self.donation_deadline or self.offer.auction.donation_deadline

    def can_donate(self, top_bids):
        check_valid = any([True for b in top_bids if b.id == self.id])
        return True if check_valid and self.donate_by > timezone.now() else False

    @property
    def hash(self):
        return BID_HASH.encode(self.id)

    @property
    def status(self):
        for state in ['donation_complete', 'donation_unverified', 'pending_alert', 'pending_donation', 'donation_late']:
            if getattr(self, state):
                return state

    @property
    def donation_complete(self):
        # donation confirmed
        return self.has_donated

    @property
    def donation_unverified(self):
        # no confirmation, but there is a receipt to confirm, so even if it's post deadline we're good
        return True if not self.donation_complete and self.receipt else False

    @property
    def pending_alert(self):
        # no confirmation, no receipt, but also no e-mail went out so deadline doesn't apply
        return True if not self.donation_complete \
                       and not self.donation_unverified \
                       and not self.winner_alert_email_date else False

    @property
    def pending_donation(self):
        # no confirmation, no receipt, email went out and we're inside the deadline, so we're waiting
        return True if not self.donation_complete \
                       and not self.donation_unverified \
                       and not self.pending_alert \
                       and timezone.now() < self.donate_by else False

    @property
    def donation_late(self):
        # no confirmation, no receipt, email went out and we're outside the deadline, so it's late
        return True if not self.donation_complete \
                       and not self.donation_unverified \
                       and not self.pending_alert \
                       and timezone.now() > self.donate_by else False

    def generate_winner_donation_alert(self):
        email = self.offer.auction.winner_alert_email_body.format(**{
            'bidder': self.user.display_name,
            'auctionee': self.offer.user.display_name,
            'category': self.offer.category.name,
            'amount': "{} ({})".format(
                format_currency(self.amount, self.offer.auction.currency),
                self.offer.auction.currency
            ),
            'deadline': "{} ({})".format(
                dateformat.format(timezone.localtime(self.donate_by), "m/d/Y H:i"),
                self.offer.auction.timezone
            ),
            'donation_instructions': self.offer.auction.beneficiary_donation_information,
            'donation_website': self.offer.auction.beneficiary_donation_website,
            'link': "{}{}".format(settings.BASE_URL, reverse('bid:donate', kwargs={
                'user': self.offer.auction.user.slug,
                'auction': self.offer.auction.slug,
                'bidder': self.offer.user.slug,
                'hash': self.hash
            }))
        })

        return str(email)

    def _auctionee_details_email(self, email):
        return str(email.format(**{
            'bidder': self.user.display_name,
            'auctionee': self.offer.user.display_name,
            'email': self.offer.user.email,
            'category': self.offer.category.name,
            'amount': "{} ({})".format(
                format_currency(self.amount, self.offer.auction.currency),
                self.offer.auction.currency
            )
        }))

    def _pinch_hitter_details_email(self, email):
        return str(email.format(**{
            'bidder': self.user.display_name,
            'auctionee': self.offer.user.display_name,
            'pinch_hitter': self.pinch_hitter.display_name,
            'email': self.offer.user.email,
            'category': self.offer.category.name,
            'amount': "{} ({})".format(
                format_currency(self.amount, self.offer.auction.currency),
                self.offer.auction.currency
            )
        }))

    # the auctionee's details to send to the winning bidder
    def generate_winner_sent_auctionee_details_email(self):
        return self._auctionee_details_email(self.offer.auction.auctionee_details_to_winner_email_body)

    # the winning bidder's details to send to the auctionee
    def generate_auctionee_sent_winner_details_email(self):
        return self._auctionee_details_email(self.offer.auction.winner_details_to_auctionee_email_body)

    # the pinch-hitter's details to send to the winning bidder
    def generate_winner_sent_pinch_hitter_details_email(self):
        return self._pinch_hitter_details_email(self.offer.auction.pinch_hitter_details_to_winner_email_body)

    # the winning bidder's details to send to the pinch-hitter
    def generate_pinch_hitter_sent_winner_details_email(self):
        return self._pinch_hitter_details_email(self.offer.auction.winner_details_to_pinch_hitter_email_body)

    # send e-mail to winning bidder with donation information
    def email_winner_donation_alert(self):
        email = EmailMessage(
            "[{}] {}".format(self.offer.auction.title, self.offer.auction.winner_alert_email_subject),
            self.winner_alert_email,
            "<Fantics> {}".format(settings.DEFAULT_FROM_EMAIL),
            to=[self.user.email],
            reply_to=["<{}> {}".format(self.offer.auction.contact_name, self.offer.auction.contact_email)]
        )

        return email.send(fail_silently=True)

    # send e-mail to auctionee with winning bidder details
    def email_winner_details_to_auctionee(self):
        email = EmailMessage(
            "[{}] {}".format(self.offer.auction.title, self.offer.auction.winner_details_to_auctionee_email_subject),
            self.auctionee_sent_winner_details_email,
            "<Fantics> {}".format(settings.DEFAULT_FROM_EMAIL),
            to=[self.user.email],
            reply_to=["<{}> {}".format(self.offer.auction.contact_name, self.offer.auction.contact_email)]
        )

        return email.send(fail_silently=True)

    # send e-mail to winning bidder with auctionee details
    def email_auctionee_details_to_winner(self):
        email = EmailMessage(
            "[{}] {}".format(self.offer.auction.title, self.offer.auction.auctionee_details_to_winner_email_subject),
            self.winner_sent_auctionee_details_email,
            "<Fantics> {}".format(settings.DEFAULT_FROM_EMAIL),
            to=[self.user.email],
            reply_to=["<{}> {}".format(self.offer.auction.contact_name, self.offer.auction.contact_email)]
        )

        return email.send(fail_silently=True)

    # send e-mail to pinch hitter with winning bidder details
    def email_winner_details_to_pinch_hitter(self):
        email = EmailMessage(
            "[{}] {}".format(self.offer.auction.title, self.offer.auction.winner_details_to_pinch_hitter_email_subject),
            self.pinch_hitter_sent_winner_details_email,
            "<Fantics> {}".format(settings.DEFAULT_FROM_EMAIL),
            to=[self.user.email],
            reply_to=["<{}> {}".format(self.offer.auction.contact_name, self.offer.auction.contact_email)]
        )

        return email.send(fail_silently=True)

    # send e-mail to winning bidder with pinch hitter details
    def email_pinch_hitter_details_to_winner(self):
        email = EmailMessage(

bid/templates/bid/delete.html
{% extends 'auction/administration/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete this bid? Once you hit the button below, it's gone-gone. Like, gone like it never was, <strong>gone</strong>.</p>
    <button type="submit" class="btn btn-danger">Super sure! Delete it!</button>
    <a class="btn btn-primary float-right" href="{% url 'auction:results' auction.user.slug auction.slug %}">Augh, stop, reverse! Reverse!</a>
</form>
{% endblock %}

bid/templates/bid/update.html
{% extends 'auction/administration/base.html' %}
{% load bootstrap4 core_tags %}

{% block javascript_body %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css">
{% endblock %}

{% block main %}
    <h1>{{ bid.user }} bidding {% currency bid.amount auction.currency %} for {{ bid.offer.user }}'s {{ bid.offer.category|lower }}</h1>
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Bidder</strong> <a href="{% url 'account:profile' bid.user.slug %}">{{ bid.user }}</a>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Auctionee</strong> <a href="{% url 'account:profile' bid.offer.user.slug %}">{{ bid.offer.user }}</a>
                </li>
                {% if bid.pinch_hitter %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Pinch-hitter</strong>
                    <div>
                        <a href="{% url 'account:profile' bid.pinch_hitter.slug %}">{{ bid.pinch_hitter }}</a>
                        <a href="{% url 'bid:remove_pinch_hit' auction.user.slug auction.slug bid.pk %}" class="text-danger" title="Remove"><i class="fa fa-times-circle-o"></i> <span class="sr-only">Remove</span></a>
                    </div>
                 </li>
                {% endif %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Offer</strong> <a href="{% url 'offer:view' auction.user.slug auction.slug bid.offer.user.slug bid.offer.pk %}"></strong> {{ bid.offer.category }}</a>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Amount</strong> {% currency bid.amount auction.currency %}
                </li>
                <li class="list-group-item">
                   <strong>Made bid</strong><br>{{ bid.created }}
                </li>
                <li class="list-group-item">
                   <strong>Donation deadline</strong><br>{{ bid.donate_by }}
                </li>
                <li class="list-group-item">
                   <strong>Donation made</strong><br>{{ bid.donated|default_if_none:"-" }}
                </li>
            </ul>
            <h4 class="mt-4 mb-2"><a href="{% url 'bid:email' auction.user.slug auction.slug bid.pk %}">E-mails</a></h4>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <strong>E-mailed about win</strong><br>{{ bid.winner_alert_email_date|default_if_none:"-" }}
                </li>
                <li class="list-group-item">
                    <strong>Winner e-mailed auctionee details</strong><br>{{ bid.winner_sent_auctionee_details_email_date|default_if_none:"-" }}
                </li>
                <li class="list-group-item">
                    <strong>Auctionee e-mailed winner details</strong><br>{{ bid.auctionee_sent_winner_details_email_date|default_if_none:"-" }}
                </li>
                {% if bid.pinch_hitter %}
                <li class="list-group-item">
                    <strong>Winner e-mailed pinch-hitter details</strong><br>{{ bid.winner_sent_pinch_hitter_details_email_date|default_if_none:"-" }}
                </li>
                <li class="list-group-item">
                    <strong>Pinch-hitter e-mailed winner details</strong><br>{{ bid.pinch_hitter_sent_winner_details_email_date|default_if_none:"-" }}
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="col-md-6">
            <form method="post" action="{% url 'bid:update' auction.user.slug auction.slug bid.pk %}">
                {% csrf_token %}
                {% bootstrap_form_errors form %}
                <fieldset>
                    <legend>Donation</legend>
                    <div class="form-group">
                        <label class="sr-only" for="id_donation_deadline">Donation deadline</label>
                        {% datetimepicker 'donation_deadline' value=bid.donation_deadline placeholder="Deadline" %}
                        <small class="form-text text-muted mb-3">Leave blank to use the default donation deadline ({{ auction.donation_deadline }})</small>
                        {% bootstrap_field form.receipt layout="inline" %}
                        {% bootstrap_field form.has_donated layout="inline" %}
                        <small class="form-text text-muted mb-3">The first time 'Has donated' is checked when the bid is updated will trigger confirmation e-mails to the auctionee and bidder.</small>
                    </div>
                </fieldset>
                {% if not bid.pinch_hitter %}
                    <fieldset>
                        <legend>Pinch hitter</legend>
                        <p class="alert alert-warning">Assigning a pinch-hitter will trigger e-mails to the pinch-hitter and the winner with each other's details.</p>
                        {% bootstrap_field form.pinch_hitter layout="inline" %}
                        <p><small class="form-text text-muted">Only users who have a verified account here can be assigned as a pinch-hitter.</small></p>
                    </fieldset>
                {% else %}
                    {% bootstrap_field form.pinch_hitter layout="inline" %}
                {% endif %}
                <button type="submit" class="btn btn-primary">Edit</button>
            </form>
        </div>
    </div>
{% endblock %}

bid/templates/bid/wins.html
{% extends 'auction/base.html' %}
{% load bootstrap4 core_tags %}

{% block main %}
    <h1>Your wins</h1>
    {% if wins %}
    <table class="table">
        <tbody>
            {% for bid in wins %}
            <tr class="table-{% if bid.donation_complete %}success{% elif bid.donation_unverified %}info{% elif bid.pending_alert %}light{% elif bid.pending_donation %}warning{% elif bid.donation_late %}danger{% endif %}">
                <td>{{ bid.offer.category }}</td>
                <td><a href="{% url 'account:profile' bid.offer.user.slug %}">{{ bid.offer.user }}</a></td>
                <td>{% currency bid.amount auction.currency %}</td>
                <td class="text-right">
                    <div class="btn-group">
                        <a href="{% url 'offer:view' auction.user.slug auction.slug bid.offer.user.slug bid.offer.pk %}" class="btn btn-info btn-sm d-flex align-items-center" title="View"><i class="fa fa-eye"></i> <span class="sr-only">View</span></a>
                        {% if not bid.pending_alert and not bid.donation_late %}
                            <a href="{% url 'bid:donate' auction.user.slug auction.slug bid.user.slug bid.hash %}" class="btn btn-warning btn-sm d-flex align-items-center" title="Donate"><i class="fa fa-star"></i> <span class="sr-only">Donate</span></a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% elif filters.all %}
        <p>There aren't any bids to view under this filter.</p>
    {% else %}
        <p>Sorry, you don't have any winning bids</p>
    {% endif %}
{% endblock %}

{% block side %}
    <h1>&nbsp;</h1>
    <div class="list-group">
        <a href="{% url 'bid:wins' auction.user.slug auction.slug request.user.slug %}" class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center list-group-item-dark">All <span class="badge badge-dark badge-pill">{{ filters.all }}</span></a>
        <a href="{% url 'bid:wins' auction.user.slug auction.slug request.user.slug %}?filter=pending_alert" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center list-group-item-light">Pending administration <span class="badge badge-secondary badge-pill">{{ filters.pending_alert }}</span></a>
        <a href="{% url 'bid:wins' auction.user.slug auction.slug request.user.slug %}?filter=pending_donation" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center list-group-item-warning">Pending donation <span class="badge badge-warning badge-pill">{{ filters.pending_donation }}</span></a>
        <a href="{% url 'bid:wins' auction.user.slug auction.slug request.user.slug %}?filter=donation_unverified" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center list-group-item-info">Donation unverified <span class="badge badge-info badge-pill">{{ filters.donation_unverified }}</span></a>
        <a href="{% url 'bid:wins' auction.user.slug auction.slug request.user.slug %}?filter=donation_complete" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center list-group-item-success">Donation complete <span class="badge badge-success badge-pill">{{ filters.donation_complete }}</span></a>
        <a href="{% url 'bid:wins' auction.user.slug auction.slug request.user.slug %}?filter=donation_late" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center list-group-item-danger">Donation late <span class="badge badge-danger badge-pill">{{ filters.donation_late }}</span></a>
    </div>
{% endblock %}