account/urls.py
from django.urls import path

from .views import (LoginView, LogoutView, RegisterView, ValidateView, ProfileView, ResendValidationView,
                    PasswordResetView, PasswordResetConfirmView, CookiesView, PasswordChangeView, AccountDeleteView,
                    AccountUpdateView)


app_name = 'account'

urlpatterns = [
    path('create-account/', RegisterView.as_view(), name='register'),
    path('validate/<slug:uidb64>/<slug:token>/', ValidateView.as_view(), name='validate'),
    path('validate/', ResendValidationView.as_view(), name='resend_validate'),
    path('login/', LoginView.as_view(), name='login'),
    path('login/password/', PasswordResetView.as_view(), name='password_reset'),
    path('login/password/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', AccountUpdateView.as_view(), name='update'),
    path('account/password/', PasswordChangeView.as_view(), name='password'),
    path('account/delete/', AccountDeleteView.as_view(), name='delete'),
    path('cookies/', CookiesView.as_view(), name='cookies'),
    path('<slug:slug>/', ProfileView.as_view(), name='profile'),
]

api/urls.py
from django.urls import (path, include)
from rest_framework import routers

from .views import (OfferViewSet, UserViewSet, AuctionViewSet, BidViewSet, CategoryViewSet)


router = routers.DefaultRouter()
router.register(r'auctions', AuctionViewSet)
router.register(r'bids', BidViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'offers', OfferViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

auction/urls.py
from django.urls import path

from .views import (AuctionView, AuctionAboutView, AuctionCreateView, AuctionUpdateView, AuctionDeleteView,
                    AuctionResultsView, AuctionUpdateEmailView, AuctionUpdateLayoutView)


app_name = 'auction'

urlpatterns = [
    path('<slug:user>/create-auction/', AuctionCreateView.as_view(), name='create'),
    path('<slug:user>/<slug:auction>/', AuctionView.as_view(), name='auction'),
    path('<slug:user>/<slug:auction>/about/', AuctionAboutView.as_view(), name='about'),
    path('<slug:user>/<slug:auction>/edit/', AuctionUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/edit/email/', AuctionUpdateEmailView.as_view(), name='update_email'),
    path('<slug:user>/<slug:auction>/edit/layout/', AuctionUpdateLayoutView.as_view(), name='update_layout'),
    path('<slug:user>/<slug:auction>/delete/', AuctionDeleteView.as_view(), name='delete'),
    path('<slug:user>/<slug:auction>/winning-bids/', AuctionResultsView.as_view(), name='results'),
]

bid/urls.py
from django.urls import path

from .views import (BidListView, BidWinView, BidUpdateView, BidDeleteView, BidEmailView, BidValidateView,
                    BidRemovePinchHitterView, BidAlertEmailView, BidConfirmEmailView, BidBulkAlertEmailView,
                    BidDonationView)


app_name = 'bid'

urlpatterns = [
    path('<slug:user>/<slug:auction>/results/bulk-email/', BidBulkAlertEmailView.as_view(), name='email_bulk_alert'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/', BidEmailView.as_view(), name='email'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/alert/', BidAlertEmailView.as_view(), name='email_alert'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/',
         BidConfirmEmailView.as_view(to_winner=True, to_auctionee=True),
         name='email_confirm'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/winner/', BidConfirmEmailView.as_view(to_winner=True), name='email_confirm_to_winner'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/auctionee/', BidConfirmEmailView.as_view(to_auctionee=True), name='email_confirm_to_auctionee'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/validate/', BidValidateView.as_view(), name='validate'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/remove-pinch-hit/',
         BidRemovePinchHitterView.as_view(),
         name='remove_pinch_hit'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/edit/', BidUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/delete/', BidDeleteView.as_view(), name='delete'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/bids/', BidListView.as_view(), name='list'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/wins/', BidWinView.as_view(), name='wins'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/wins/<slug:hash>/', BidDonationView.as_view(), name='donate'),
]

fantics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import (include, path)
from django.views.generic import RedirectView


urlpatterns = [
    path('hijack/', include('hijack.urls', namespace='hijack')),
    # path('api/v1/', include('api.urls')),
    path('', include('main.urls', namespace="main")),
    path('', include('message.urls', namespace="message")),
    path('', include('account.urls', namespace="account")),
    path('', include('auction.urls', namespace="auction")),
    path('', include('bid.urls', namespace="bid")),
    path('', include('category.urls', namespace="category")),
    path('', include('offer.urls', namespace="offer")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
        + urlpatterns

main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import HomeView


app_name = 'main'

urlpatterns = [
    path('about/', TemplateView.as_view(template_name='main/brochure/about.html'), name='about'),
    path('support/', TemplateView.as_view(template_name='main/brochure/support.html'), name='support'),
    path('privacy-policy/', TemplateView.as_view(template_name='main/brochure/privacy_policy.html'),
         name='privacy_policy'),
    path('terms-of-use/', TemplateView.as_view(template_name='main/brochure/terms_of_use.html'), name='terms_of_use'),
    path('', HomeView.as_view(), name='home')
]

offer/urls.py
from django.urls import path

from .views import (OfferView, OfferCreateView, OfferListView, OfferUpdateView, OfferDeleteView,
                    OfferListAdministrationView, OfferUpdateAdministrationView, OfferDeleteAdministrationView,
                    OfferSearchView)


app_name = 'offer'

urlpatterns = [
    path('<slug:user>/<slug:auction>/create-offer/', OfferCreateView.as_view(), name='create'),
    path('<slug:user>/<slug:auction>/offers/', OfferListAdministrationView.as_view(), name='list_administration'),
    path('<slug:user>/<slug:auction>/offers/<slug:category>/', OfferListAdministrationView.as_view(),
         name='list_administration_category'),
    path('<slug:user>/<slug:auction>/offer/<int:pk>/edit/', OfferUpdateAdministrationView.as_view(),
         name='update_administration'),
    path('<slug:user>/<slug:auction>/offer/<int:pk>/delete/', OfferDeleteAdministrationView.as_view(),
         name='delete_administration'),
    path('<slug:user>/<slug:auction>/tag:<slug:tag>/', OfferSearchView.as_view(), name='search_tag'),
    path('<slug:user>/<slug:auction>/category:<slug:category>/', OfferSearchView.as_view(), name='search_category'),
    path('<slug:user>/<slug:auction>/category:<slug:category>/tag:<slug:tag>/', OfferSearchView.as_view(),
         name='search_items'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/', OfferListView.as_view(), name='list'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/', OfferView.as_view(), name='view'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/edit/', OfferUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/delete/', OfferDeleteView.as_view(), name='delete'),
]

main/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm, UserChangeForm)
from django.shortcuts import reverse
from django.utils.html import mark_safe
from django.utils.translation import ugettext_lazy as _

from .models import User


class LoginForm(AuthenticationForm):
    remember = forms.BooleanField(widget=forms.CheckboxInput(), initial=False,
                                  label=_('Remember me'), required=False)


class RegisterForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput())
    age = forms.BooleanField(widget=forms.CheckboxInput(), label="I'm 13 or older")
    terms_of_use = forms.BooleanField(widget=forms.CheckboxInput(), label="")

    def clean_display_name(self):
        user = User.objects.filter(display_name__iexact=self.cleaned_data.get('display_name'))

        if user.count():
            raise forms.ValidationError('A user with this display name already exists',
                                        'not_unique',
                                        params=['display_name', ])

        return self.cleaned_data.get('display_name')

    class Meta:
        model = User
        fields = ('email', 'username', 'display_name', 'password1', 'password2', 'age', 'terms_of_use')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['terms_of_use'].label = mark_safe("I agree with the <a href='{}' target='_blank'>Terms of Use</a>".format(
            reverse('main:terms_of_use'))
        )


class AccountForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput)
    website = forms.URLField(widget=forms.URLInput(attrs={'placeholder': 'http://www.yourwebsite.com'}), required=False)

    class Meta:
        model = User
        fields = ['email', 'username', 'display_name', 'tumblr', 'website', 'twitter', 'pillowfort',
                  'dreamwidth', 'ao3', 'livejournal', 'icon']

    def clean_display_name(self):
        user = User.objects.\
            filter(display_name__iexact=self.cleaned_data.get('display_name'))\
            .exclude(pk=self.instance.pk)

        if user.count():
            raise forms.ValidationError('A user with this display name already exists',
                                        'not_unique',
                                        params=['display_name', ])

        return self.cleaned_data.get('display_name')


class DeleteForm(forms.ModelForm):
    is_active = forms.BooleanField(widget=forms.HiddenInput)

    class Meta:
        model = User
        fields = ['is_active', ]

    def clean_is_active(self):
        return False


class CookieForm(forms.Form):
    necessary = forms.BooleanField(widget=forms.CheckboxInput(attrs={'checked': True, 'disabled': True}),
                                   required=False)
    preferences = forms.BooleanField(widget=forms.CheckboxInput, required=False)
    analytics = forms.BooleanField(widget=forms.CheckboxInput, required=False)

main/views.py
from django.views.generic import ListView
from django.utils import timezone

from auction.models import Auction


class HomeView(ListView):
    template_name = 'main/brochure/home.html'
    model = Auction

    def get_queryset(self):
        return super().get_queryset().filter(bidding_ends__gte=timezone.now(), is_listed=True)

main/templates/main/_footer.html
<footer class="footer bg-dark">
    <div class="container">
        {% with request.resolver_match.namespace as namespace %}
        {% with request.resolver_match.url_name as name %}
        <nav class="nav">
            <a class="nav-link{% if namespace == "main" and name == "home" %} active{% endif %}" href="{% url 'main:home' %}"><i class="fa fa-home"></i> Home{% if namespace == "main" and name == "home" %}<span class="sr-only">(current)</span>{% endif %}</a>
            <a class="nav-link{% if namespace == "main" and name == "about" %} active{% endif %}" href="{% url 'main:about' %}"><i class="fa fa-info-circle"></i> About{% if namespace == "main" and name == "about" %}<span class="sr-only">(current)</span>{% endif %}</a>
            <a class="nav-link{% if namespace == "main" and name == "support" %} active{% endif %}" href="{% url 'main:support' %}"><i class="fa fa-question-circle"></i> Support{% if namespace == "main" and name == "support" %}<span class="sr-only">(current)</span>{% endif %}</a>
            <a class="nav-link{% if namespace == "main" and name == "privacy_policy" %} active{% endif %}" href="{% url 'main:privacy_policy' %}"><i class="fa fa-lock"></i> Privacy policy{% if namespace == "main" and name == "privacy_policy" %}<span class="sr-only">(current)</span>{% endif %}</a>
            <a class="nav-link{% if namespace == "main" and name == "terms_of_use" %} active{% endif %}" href="{% url 'main:terms_of_use' %}"><i class="fa fa-file-text-o"></i> Terms of use{% if namespace == "main" and name == "terms_of_use" %}<span class="sr-only">(current)</span>{% endif %}</a>
            <a class="nav-link{% if namespace == "account" and name == "cookies" %} active{% endif %}" href="{% url 'account:cookies' %}"><i class="fa fa-user-circle-o"></i> Cookies{% if namespace == "account" and name == "cookies" %}<span class="sr-only">(current)</span>{% endif %}</a>
        </nav>
        {% endwith %}
        {% endwith %}
    </div>
</footer>

main/templates/main/_navigation.html
{% with request.resolver_match.namespace as namespace %}
{% with request.resolver_match.url_name as name %}
<ul class="navbar-nav mr-2">
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <div class="btn-group my-1">
                <a href="{% url 'account:profile' request.user.slug %}" class="btn btn-secondary">
                    <span class="d-block d-sm-none"><i class="fa fa-user"></i></span>
                    <span class="d-none d-xs-block d-sm-block">{{ request.user }}</span>
                </a>
                <a href="{% url 'message:list' %}" class="btn btn-{% if request.user.count_unread_messages %}warning{% else %}info{% endif %} d-flex align-items-center">
                    <i class="fa fa-envelope-o"></i> {% if request.user.count_unread_messages %}<span class="ml-2">({{ request.user.count_unread_messages }})</span>{% endif %}
                </a>
                <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    {% for auction in request.user.auctions.all %}
                        <div class="dropdown-item d-flex align-items-center">
                            <a href="{% url 'auction:auction' auction.user.slug auction.slug %}" class="flex-grow-1 w-100 mr-5">{{ auction }}</a>
                            <a href="{% url 'auction:update' auction.user.slug auction.slug %}" class="ml-3 flex-shrink-1 btn btn-secondary" title="Settings"><i class="fa fa-cog"></i></a>
                        </div>
                        {% if forloop.last %}
                        <div class="dropdown-divider"></div>
                        {% endif %}
                    {% endfor %}
                    <a class="dropdown-item" href="{% url 'auction:create' request.user.slug %}"><i class="fa fa-star fa-fw"></i> Create new auction</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account:update' %}"><i class="fa fa-user fa-fw"></i> Account</a>
                    <a class="dropdown-item" href="{% url 'account:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Log out</a>
                </div>
            </div>
        </li>
    {% else %}
        <li class="nav-item dropdown">
            <a class="nav-link" id="dropdownLoginMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" role="button" href="{% url 'account:login' %}">Log in</a>
            <form action="{% url 'account:login' %}" method="post" class="dropdown-menu dropdown-menu-right p-4" aria-labelledby="dropdownLoginMenu">
                <div class="form-group">
                    <label for="id_username" class="sr-only">Username</label>
                    <input type="text" name="username" class="form-control" id="id_username" placeholder="Username">
                </div>
                <div class="form-group">
                    <label for="id_password" class="sr-only">Password</label>
                    <input type="password" name="password" class="form-control" id="id_password" placeholder="Password">
                </div>
                <div class="form-check">
                    <input type="checkbox" name="remember" class="form-check-input" id="id_remember">
                    <label class="form-check-label" for="id_remember">Remember me</label>
                </div>
                <button type="submit" class="btn btn-primary mt-3"><i class="fa fa-power-off"></i> Log in</button>
                {% csrf_token %}
            </form>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account:register' %}">Get started</a>
        </li>
    {% endif %}
</ul>
{% endwith %}
{% endwith %}

main/templates/main/base.html
{% extends 'base.html' %}
{% load bootstrap4 static_version %}

{% block css %}
    <link rel="stylesheet" href="{% static_version 'main/css/site.css' %}">
{% endblock %}

{% block body %}
    {% block navigation %}
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'main:home' %}">Fantics</a>
        <span class="mr-auto"></span>
        {% include 'main/_navigation.html' %}
    </nav>
    {% endblock %}
    {% block container %}
    <div class="container my-5" role="main">
        {% if user.is_validating and not messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <h4 class="alert-heading">Validate</h4>
                You shoooould have received one of those "yeah, it's me" e-mails at <strong>{{ request.user.email }}</strong> when you registered - give the link inside it a click and this will disappear.
                If you didn't, <a href="{% url 'account:resend_validate' %}" class="alert-link">click here to send the e-mail</a> again.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
        {% endif %}
        {% bootstrap_messages %}
        {% block content %}
        <div class="row">
            <div class="col-md-9">{% block main %}{% endblock %}</div>
            <div class="col-md-3">{% block side %}{% endblock %}</div>
        </div>
        {% endblock %}
    </div>
    {% endblock %}
    {% block footer %}
    {% include 'main/_footer.html' %}
    {% endblock %}
{% endblock %}