api/urls.py
from django.urls import (path, include)
from rest_framework import routers

from .views import (OfferViewSet, UserViewSet, AuctionViewSet, BidViewSet, CategoryViewSet)


router = routers.DefaultRouter()
router.register(r'auctions', AuctionViewSet)
router.register(r'bids', BidViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'offers', OfferViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

auction/urls.py
from django.urls import path

from .views import (AuctionView, AuctionAboutView, AuctionCreateView, AuctionUpdateView, AuctionDeleteView,
                    AuctionResultsView, AuctionUpdateEmailView, AuctionUpdateLayoutView)


app_name = 'auction'

urlpatterns = [
    path('<slug:user>/create-auction/', AuctionCreateView.as_view(), name='create'),
    path('<slug:user>/<slug:auction>/', AuctionView.as_view(), name='auction'),
    path('<slug:user>/<slug:auction>/about/', AuctionAboutView.as_view(), name='about'),
    path('<slug:user>/<slug:auction>/edit/', AuctionUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/edit/email/', AuctionUpdateEmailView.as_view(), name='update_email'),
    path('<slug:user>/<slug:auction>/edit/layout/', AuctionUpdateLayoutView.as_view(), name='update_layout'),
    path('<slug:user>/<slug:auction>/delete/', AuctionDeleteView.as_view(), name='delete'),
    path('<slug:user>/<slug:auction>/winning-bids/', AuctionResultsView.as_view(), name='results'),
]

bid/urls.py
from django.urls import path

from .views import (BidListView, BidWinView, BidUpdateView, BidDeleteView, BidEmailView, BidValidateView,
                    BidRemovePinchHitterView, BidAlertEmailView, BidConfirmEmailView, BidBulkAlertEmailView,
                    BidDonationView)


app_name = 'bid'

urlpatterns = [
    path('<slug:user>/<slug:auction>/results/bulk-email/', BidBulkAlertEmailView.as_view(), name='email_bulk_alert'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/', BidEmailView.as_view(), name='email'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/alert/', BidAlertEmailView.as_view(), name='email_alert'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/',
         BidConfirmEmailView.as_view(to_winner=True, to_auctionee=True),
         name='email_confirm'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/winner/', BidConfirmEmailView.as_view(to_winner=True), name='email_confirm_to_winner'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/email/confirm/auctionee/', BidConfirmEmailView.as_view(to_auctionee=True), name='email_confirm_to_auctionee'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/validate/', BidValidateView.as_view(), name='validate'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/remove-pinch-hit/',
         BidRemovePinchHitterView.as_view(),
         name='remove_pinch_hit'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/edit/', BidUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/results/<int:pk>/delete/', BidDeleteView.as_view(), name='delete'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/bids/', BidListView.as_view(), name='list'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/wins/', BidWinView.as_view(), name='wins'),
    path('<slug:user>/<slug:auction>/<slug:bidder>/wins/<slug:hash>/', BidDonationView.as_view(), name='donate'),
]

fantics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import (include, path)
from django.views.generic import RedirectView


urlpatterns = [
    path('hijack/', include('hijack.urls', namespace='hijack')),
    # path('api/v1/', include('api.urls')),
    path('', include('main.urls', namespace="main")),
    path('', include('message.urls', namespace="message")),
    path('', include('account.urls', namespace="account")),
    path('', include('auction.urls', namespace="auction")),
    path('', include('bid.urls', namespace="bid")),
    path('', include('category.urls', namespace="category")),
    path('', include('offer.urls', namespace="offer")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
        + urlpatterns

offer/urls.py
from django.urls import path

from .views import (OfferView, OfferCreateView, OfferListView, OfferUpdateView, OfferDeleteView,
                    OfferListAdministrationView, OfferUpdateAdministrationView, OfferDeleteAdministrationView,
                    OfferSearchView)


app_name = 'offer'

urlpatterns = [
    path('<slug:user>/<slug:auction>/create-offer/', OfferCreateView.as_view(), name='create'),
    path('<slug:user>/<slug:auction>/offers/', OfferListAdministrationView.as_view(), name='list_administration'),
    path('<slug:user>/<slug:auction>/offers/<slug:category>/', OfferListAdministrationView.as_view(),
         name='list_administration_category'),
    path('<slug:user>/<slug:auction>/offer/<int:pk>/edit/', OfferUpdateAdministrationView.as_view(),
         name='update_administration'),
    path('<slug:user>/<slug:auction>/offer/<int:pk>/delete/', OfferDeleteAdministrationView.as_view(),
         name='delete_administration'),
    path('<slug:user>/<slug:auction>/tag:<slug:tag>/', OfferSearchView.as_view(), name='search_tag'),
    path('<slug:user>/<slug:auction>/category:<slug:category>/', OfferSearchView.as_view(), name='search_category'),
    path('<slug:user>/<slug:auction>/category:<slug:category>/tag:<slug:tag>/', OfferSearchView.as_view(),
         name='search_items'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/', OfferListView.as_view(), name='list'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/', OfferView.as_view(), name='view'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/edit/', OfferUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/delete/', OfferDeleteView.as_view(), name='delete'),
]

auction/models.py
import pytz

from decimal import Decimal

from django.db import models
from django.utils import (timezone, dateformat)
from django.utils.functional import cached_property

from autoslugged import AutoSlugField

from category.models import Category
from core.models import Currency
from core.helpers import file_name
from offer.models import Offer


class AuctionQuerySet(models.QuerySet):
    def with_related_offers(self):
        return self \
            .prefetch_related('categories')\
            .prefetch_related('offers') \
            .prefetch_related('offers__category') \
            .prefetch_related('offers__user') \
            .prefetch_related('offers__tags') \
            .prefetch_related('offers__bids')


class AuctionManager(models.Manager):
    def get_queryset(self):
        return AuctionQuerySet(self.model, using=self._db)\
            .filter(is_active=True)\
            .order_by('-bidding_ends')\
            .select_related('user')\
            .annotate(
                currency_rate=models.Subquery(Currency.objects.filter(code=models.OuterRef('currency')).values('rate')),
                count_categories=models.Count('categories', distinct=True),
                count_offers=models.Count('offers', distinct=True),
            ).distinct()

    def with_related_offers(self):
        return self.get_queryset().with_related_offers()


def auction_icon_name(instance, filename):
    return '/'.join(['auction', 'icons', file_name(filename)])


def auction_logo_name(instance, filename):
    return '/'.join(['auction', 'logo', file_name(filename)])


def auction_banner_name(instance, filename):
    return '/'.join(['auction', 'banners', file_name(filename)])


def auction_beneficiary_name(instance, filename):
    return '/'.join(['auction', 'beneficiaries', file_name(filename)])


class Auction(models.Model):
    user = models.ForeignKey('account.User', related_name='auctions', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from='title', unique_with='user', always_update=True)

    contact_name = models.CharField(max_length=255)
    contact_email = models.EmailField(max_length=255)

    css = models.TextField(blank=True)
    header = models.TextField(blank=True)
    footer = models.TextField(blank=True)

    icon = models.ImageField(null=True, blank=True, upload_to=auction_icon_name, help_text='max. 100x100')
    logo = models.ImageField(null=True, blank=True, upload_to=auction_logo_name, help_text='max. 300x100')
    banner = models.ImageField(null=True, blank=True, upload_to=auction_banner_name, help_text='max. 1140x200')

    is_listed = models.BooleanField(default=True, db_index=True,
                                    help_text='Show on your profile and other public areas')
    is_active = models.BooleanField(default=True, db_index=True)

    signup_starts = models.DateTimeField(null=True, blank=True)
    signup_ends = models.DateTimeField(null=True, blank=True)
    bidding_starts = models.DateTimeField(null=True, blank=True)
    bidding_ends = models.DateTimeField(null=True, blank=True)
    offer_deadline = models.DateField(null=True, blank=True)
    donation_deadline = models.DateTimeField(null=True, blank=True)

    signup_email_subject = models.CharField(blank=True, max_length=255)
    signup_email_body = models.TextField(blank=True)

    bid_email_subject = models.CharField(blank=True, max_length=255)
    bid_email_body = models.TextField(blank=True)

    overbid_email_subject = models.CharField(blank=True, max_length=255)
    overbid_email_body = models.TextField(blank=True)

    winner_alert_email_subject = models.CharField(blank=True, max_length=255)
    winner_alert_email_body = models.TextField(blank=True)

    winner_details_to_auctionee_email_subject = models.CharField(blank=True, max_length=255)
    winner_details_to_auctionee_email_body = models.TextField(blank=True)

    auctionee_details_to_winner_email_subject = models.CharField(blank=True, max_length=255)
    auctionee_details_to_winner_email_body = models.TextField(blank=True)

    pinch_hitter_details_to_winner_email_subject = models.CharField(blank=True, max_length=255)
    pinch_hitter_details_to_winner_email_body = models.TextField(blank=True)

    winner_details_to_pinch_hitter_email_subject = models.CharField(blank=True, max_length=255)
    winner_details_to_pinch_hitter_email_body = models.CharField(blank=True, max_length=255)

    allow_custom_offer_deadline = models.BooleanField(default=False,
                                                      help_text='The person making the offer sets their own deadline')

    max_offers_per_user = models.IntegerField(null=True, blank=True)
    max_quantity_per_offer = models.IntegerField(null=True, blank=True)

    currency = models.CharField(max_length=3, default="USD")
    timezone = models.CharField(choices=[(tz, tz) for tz in pytz.common_timezones], max_length=255, default="UTC")

    beneficiary_name = models.CharField(max_length=255)
    beneficiary_description = models.TextField(blank=True)
    beneficiary_website = models.URLField(max_length=255, blank=True)
    beneficiary_image = models.ImageField(null=True, blank=True, upload_to=auction_beneficiary_name,
                                          help_text='max. 600x600')
    beneficiary_donation_website = models.URLField(max_length=255, blank=True)
    beneficiary_donation_information = models.TextField(blank=True)

    about = models.TextField(blank=True)

    target = models.DecimalField(default=Decimal("0.00"), decimal_places=2, max_digits=8)

    created = models.DateTimeField(auto_now_add=True)

    objects = AuctionManager()

    def __str__(self):
        return self.title

    @property
    def exchange(self):
        return Currency(code=self.currency, rate=self.currency_rate)

    @staticmethod
    def _period(starts, ends):
        if not starts or not ends:
            return None

        if starts.month == ends.month and starts.year == ends.year:
            return "{} to {}".format(
                dateformat.format(starts, "jS"),
                dateformat.format(ends, "jS M Y"),
            )

        elif starts.year == ends.year:
            return "{} to {}".format(
                dateformat.format(starts, "jS M"),
                dateformat.format(ends, "jS M Y")
            )

        else:
            return "{} - {}".format(
                dateformat.format(starts, "jS M Y"),
                dateformat.format(ends, "jS M Y")
            )

    @property
    def auction_period(self):
        return self._period(self.signup_starts, self.bidding_ends)

    @property
    def signup_period(self):
        return self._period(self.signup_starts, self.signup_ends)

    @property
    def bidding_period(self):
        return self._period(self.bidding_starts, self.bidding_ends)

    @property
    def signups_open(self):
        if not self.signup_starts \
                or not self.signup_ends \
                or not (self.signup_starts <= timezone.now() <= self.signup_ends):
            return False

        return True

    @property
    def bidding_open(self):
        if not self.bidding_starts \
                or not self.bidding_ends \
                or not (self.bidding_starts <= timezone.now() <= self.bidding_ends):
            return False

        return True

    @property
    def pending(self):
        if not self.auction_period \
                or not self.beneficiary_donation_information \
                or not self.beneficiary_donation_website \
                or (self.signup_starts and self.signup_starts > timezone.now()):
            return True

        return False

    @property
    def complete(self):
        return bool(self.bidding_ends and timezone.now() > self.bidding_ends)

    @property
    def show_nav_offers(self):
        return bool(self.signup_starts and timezone.now() > self.signup_starts) and not self.show_nav_winners

    @property
    def show_nav_bids(self):
        return bool(self.bidding_starts and timezone.now() > self.bidding_starts) and not self.show_nav_wins

    @property
    def show_nav_wins(self):
        return bool(self.bidding_ends and timezone.now() > self.bidding_ends) and self.top_bids

    @property
    def show_nav_winners(self):
        return bool(self.bidding_ends and timezone.now() > self.bidding_ends)

    @property
    def can_send_email_winner_alerts(self):
        if not self.complete or not self.top_bids or any([True for b in self.top_bids if b.winner_alert_email_date]):
            return False

        return True

    @cached_property
    def top_bids(self):
        bids = []

        for offer in self.offers.all():
            if offer.top_bids:
                bids = bids + offer.top_bids

        return bids

    @cached_property
    def total(self):
        total = 0

        for offer in self.offers.all():
            for bid in offer.top_bids:
                total += bid.amount

        return total

    @cached_property
    def donated(self):
        total = 0

        for offer in self.offers.all():
            for bid in offer.top_bids:
                if bid.has_donated:
                    total += bid.amount

        return total

    @property
    def is_archived(self):
        return bool(self.donated and self.donated == self.total)

auction/templates/auction/administration/base.html
{% extends 'auction/base.html' %}
{% load static_version core_tags %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static_version 'auction/css/administration.css' %}">
{% endblock %}

{% block side %}
    <div class="list-group">
        {% with request.resolver_match.namespace as namespace %}
        {% with request.resolver_match.url_name as name %}
        <a class="list-group-item list-group-item-action{% if namespace == "auction" and name == "update" %} active{% endif %}" href="{% url 'auction:update' auction.user.slug auction.slug %}">
            <i class="fa fa-fw fa-cog"></i> Settings {% if namespace == "auction" and name == "update" %}<span class="sr-only">(current)</span>{% endif %}
        </a>
        <a class="list-group-item list-group-item-action pl-5{% if namespace == "auction" and name == "update_email" %} active{% endif %}" href="{% url 'auction:update_email' auction.user.slug auction.slug %}">
            <i class="fa fa-fw fa-envelope-o"></i> Automated e-mails {% if namespace == "auction" and name == "update_email" %}<span class="sr-only">(current)</span>{% endif %}
        </a>
        <a class="list-group-item list-group-item-action pl-5{% if namespace == "category" %} active{% endif %}" href="{% url 'category:list' auction.user.slug auction.slug %}">
            <i class="fa fa-fw fa-cubes"></i> Categories {% if namespace == "category" %}<span class="sr-only">(current)</span>{% endif %}
        </a>
        <a class="list-group-item list-group-item-action pl-5{% if namespace == "auction" and name == "update_layout" %} active{% endif %}" href="{% url 'auction:update_layout' auction.user.slug auction.slug %}">
            <i class="fa fa-fw fa-paint-brush"></i> Layout {% if namespace == "auction" and name == "update_layout" %}<span class="sr-only">(current)</span>{% endif %}
        </a>
        {% if auction.count_offers %}
        <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center{% if namespace == "offer" %} active{% endif %}" href="{% url 'offer:list_administration' auction.user.slug auction.slug %}">
            <span><i class="fa fa-fw fa-gift"></i> Offers {% if namespace == "offer" and name == "list_administration" %}<span class="sr-only">(current)</span>{% endif %}</span> <span class="badge badge-dark badge-pill">{{ auction.count_offers }}</span>
        </a>
        {% endif %}
        {% if auction.show_nav_wins %}
        <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center{% if namespace == "auction" and name == "results" %} active{% elif namespace == "bid" and name == "update" %} active{% elif namespace == "bid" and name == "email" %} active{% endif %}" href="{% url 'auction:results' auction.user.slug auction.slug %}">
            <span><i class="fa fa-fw fa-trophy"></i> Winning bids {% if namespace == "auction" and name == "results" %}<span class="sr-only">(current)</span>{% endif %}</span> <span class="badge badge-dark badge-pill">{{ auction.top_bids|length }}</span>
        </a>
        {% endif %}
        {% endwith %}
        {% endwith %}
    </div>
    {% if not auction.donated %}
        <hr>
        <p class="text-center"><a href="{% url 'auction:delete' auction.user.slug auction.slug %}" class="btn btn-warning"><i class="fa fa-trash"></i> Delete</a></p>
    {% endif %}
{% endblock %}

auction/templates/auction/administration/create.html
{% extends 'main/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <form method="post" action="{% url 'auction:create' request.user.slug %}">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
{% endblock %}

auction/templates/auction/administration/delete.html
{% extends 'auction/administration/base.html' %}

{% block main %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete <strong>{{ auction }}</strong>? Once you hit the button below, it's gone-gone. Like, gone like it never was, <strong>gone</strong>.</p>
    <button type="submit" class="btn btn-danger">Super sure! Delete it!</button>
    <a class="btn btn-primary float-right" href="{% url 'auction:update' auction.user.slug auction.slug %}">Augh, stop, reverse! Reverse!</a>
</form>
{% endblock %}

auction/templates/auction/administration/results.html
{% extends 'auction/administration/base.html' %}
{% load bootstrap4 core_tags %}

{% block main %}

<h1>
    Winning bids
    {% if auction.total and auction.donated %}
        <span class="float-md-right text-muted">
            <span class="text-success">{% currency auction.donated auction.currency %}</span>
            {% if not auction.is_archived %}
                of {% currency auction.total auction.currency %}
            {% endif %}
        </span>
    {% endif %}
</h1>

{% if auction.can_send_email_winner_alerts %}
    <div class="alert alert-success" role="alert">
        <h5 class="alert-header"><i class="fa fa-star"></i> Alert the winners!</h5>
        <hr>
        <p>You can send all the "you won, now donate!" e-mails at once by clicking the button below. <strong>This option is only available once</strong>. If anyone doesn't receive their e-mail, use the
        <i class="fa fa-envelope" title="E-mail"></i> <span class="sr-only">E-mail</span> menu options next to each individual bid to either send that e-mail again, or view the full text
        and send manually.</p>
        <p><a href="{% url 'bid:email_bulk_alert' auction.user.slug auction.slug %}" class="btn btn-success"><i class="fa fa-paper-plane"></i> Bulk send winner alerts now</a></p>
    </div>
{% else %}
    {% if filters.pending_alert %}
        <div class="alert alert-light alert-dismissible fade show" role="alert">
            <h5 class="alert-header"><i class="fa fa-exclamation-triangle"></i> <strong>{{ filters.pending_alert }} winning bidder{% if filters.pending_alert > 1 %}s{% endif %}</strong> {% if filters.pending_alert > 1 %}haven't{% else %}hasn't{% endif %}
                been sent the e-mail to donate!</h5>
            <hr>
            <p>Click <a href="{% url 'auction:results' auction.user.slug auction.slug %}?filter=pending_alert" class="alert-link"><strong>Pending alert</strong></a> to the right to view,
                then use the <i class="fa fa-envelope" title="E-mail"></i> <span class="sr-only">E-mail</span> menu options.</p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    {% if filters.donation_unverified %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            <h5 class="alert-header"><i class="fa fa-exclamation-triangle"></i> <strong>{{ filters.donation_unverified }} unverified donation{% if filters.donation_unverified > 1 %}s{% endif %}!</strong></h5>
            <hr>
            <p>Click <a href="{% url 'auction:results' auction.user.slug auction.slug %}?filter=donation_unverified" class="alert-link"><strong>Donation unverified</strong></a> to the right to view,
                then click the <i class="fa fa-star-o" title="Validate"></i> <span class="sr-only">Validate</span> to validate if you're sure it's fine, or
                <i class="fa fa-pencil" title="Edit"></i> <span class="sr-only">Edit</span> to view the provided receipt.</p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    {% if filters.donation_late %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h5 class="alert-header"><i class="fa fa-exclamation-triangle"></i> <strong>{{ filters.donation_late }} winner{% if filters.donation_late > 1 %}s</strong> haven't{% else %}</strong> hasn't{% endif %} made the donation deadline!</h5>
            <hr>
            <p>Click <a href="{% url 'auction:results' auction.user.slug auction.slug %}?filter=donation_late" class="alert-link">Donation late</a> to the right to view,
                then click <i class="fa fa-trash" title="Delete"></i> <span class="sr-only">Delete</span> to delete or <i class="fa fa-pencil" title="Edit"></i> <span class="sr-only">Edit</span> to
                extend their deadline if you prefer. If you delete, the next highest bidder will appear and need their alert e-mail sending.</p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
{% endif %}

    <table class="table">
    <thead>
        <tr>
            <th>Item</th>
            <th>Offered by</th>
            <th>Bid</th>
            <th>Bidder</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for bid in top_bids %}
        <tr class="table-{% if bid.donation_complete %}success{% elif bid.donation_unverified %}info{% elif bid.pending_alert %}light{% elif bid.pending_donation %}warning{% elif bid.donation_late %}danger{% endif %}">
            <td>{{ bid.offer.category }}</td>
            <td>{{ bid.offer.user }}</td>
            <td>{% currency bid.amount auction.currency %}</td>
            <td>{{ bid.user }}</td>
            <td class="text-right">
                <div class="btn-group">
                    <a href="{% url 'bid:update' auction.user.slug auction.slug bid.pk %}" class="btn btn-dark btn-sm d-flex align-items-center" title="Edit"><i class="fa fa-pencil"></i> <span class="sr-only">Edit</span></a>
                    {% if not bid.donation_complete %}
                    <a href="{% url 'bid:delete' auction.user.slug auction.slug bid.pk %}" class="btn btn-warning btn-sm d-flex align-items-center" title="Delete"><i class="fa fa-trash"></i> <span class="sr-only">Delete</span></a>
                    {% endif %}
                    {% if not bid.has_donated %}
                    <a href="{% url 'bid:validate' auction.user.slug auction.slug bid.pk %}" class="btn btn-info btn-sm d-flex align-items-center" title="Validate"><i class="fa fa-star-o"></i> <span class="sr-only">Validate</span></a>
                    {% endif %}
                    <a href="#" role="button" class="btn btn-primary btn-sm dropdown-toggle" title="E-mail" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-envelope"></i> <span class="sr-only">E-mail</span></a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'bid:email' auction.user.slug auction.slug bid.pk %}"><i class="fa fa-fw fa-envelope-o"></i> View e-mails</a>
                        {% if not bid.donation_complete %}
                            <a class="dropdown-item" href="{% url 'bid:email_alert' auction.user.slug auction.slug bid.pk %}"><i class="fa fa-fw fa-paper-plane"></i> Send win alert to bidder{% if bid.winner_alert_email_date %} again{% endif %}</a>
                        {% else %}
                            {% if bid.pinch_hitter %}
                                <a class="dropdown-item" href="{% url 'bid:email_confirm_to_winner' auction.user.slug auction.slug bid.pk %}"><i class="fa fa-fw fa-paper-plane"></i> Send pinch hitter's details to winner{% if bid.winner_sent_auctionee_details_email_date %} again{% endif %}</a>
                                <a class="dropdown-item" href="{% url 'bid:email_confirm_to_auctionee' auction.user.slug auction.slug bid.pk %}"><i class="fa fa-fw fa-paper-plane"></i> Send winner's details to pinch hitter{% if bid.auctionee_sent_winner_details_email_date %} again{% endif %}</a>
                            {% else %}
                                <a class="dropdown-item" href="{% url 'bid:email_confirm_to_winner' auction.user.slug auction.slug bid.pk %}"><i class="fa fa-fw fa-paper-plane"></i> Send auctionee's details to winner{% if bid.winner_sent_auctionee_details_email_date %} again{% endif %}</a>
                                <a class="dropdown-item" href="{% url 'bid:email_confirm_to_auctionee' auction.user.slug auction.slug bid.pk %}"><i class="fa fa-fw fa-paper-plane"></i> Send winner's details to auctionee{% if bid.auctionee_sent_winner_details_email_date %} again{% endif %}</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block side %}
    {{ block.super }}
    <div class="list-group mt-3">
        <a href="{% url 'auction:results' auction.user.slug auction.slug %}" class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center list-group-item-dark">All <span class="badge badge-dark badge-pill">{{ auction.top_bids|length }}</span></a>
        <a href="{% url 'auction:results' auction.user.slug auction.slug %}?filter=pending_alert" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center list-group-item-light">Pending alert <span class="badge badge-secondary badge-pill">{{ filters.pending_alert }}</span></a>
        <a href="{% url 'auction:results' auction.user.slug auction.slug %}?filter=pending_donation" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center list-group-item-warning">Pending donation <span class="badge badge-warning badge-pill">{{ filters.pending_donation }}</span></a>
        <a href="{% url 'auction:results' auction.user.slug auction.slug %}?filter=donation_unverified" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center list-group-item-info">Donation unverified <span class="badge badge-info badge-pill">{{ filters.donation_unverified }}</span></a>
        <a href="{% url 'auction:results' auction.user.slug auction.slug %}?filter=donation_complete" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center list-group-item-success">Donation complete <span class="badge badge-success badge-pill">{{ filters.donation_complete }}</span></a>
        <a href="{% url 'auction:results' auction.user.slug auction.slug %}?filter=donation_late" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center list-group-item-danger">Donation late <span class="badge badge-danger badge-pill">{{ filters.donation_late }}</span></a>
    </div>
{% endblock %}